services:
  jupyter:
    build: .
    container_name: mission2_jupyter
    ports:
      - "8882:8888"
    volumes:
      - .:/app
    networks:
      - mission2_net

networks:
  mission2_net:
    driver: bridge
